"""
当前板机联调默认值。

这些常量用于把已经确认可用的板端参数统一到运行入口、WebUI 和基础测试脚本。
"""

DEFAULT_BOARD_CAMERA_ID = "/dev/video52"
DEFAULT_BOARD_CAMERA_FPS = 30
DEFAULT_BOARD_CAMERA_WEB_FPS = 8
DEFAULT_BOARD_CAMERA_CLASSIFICATION_FPS = 6
DEFAULT_BOARD_CAMERA_WIDTH = 640
DEFAULT_BOARD_CAMERA_HEIGHT = 480
DEFAULT_BOARD_CAMERA_FORMAT = "MJPG"
DEFAULT_BOARD_RUNTIME_CENTER_HOLD_FRAMES = 1
DEFAULT_BOARD_RUNTIME_STOP_ON_FIRST_DETECTION = True
DEFAULT_BOARD_RUNTIME_DETECTION_STOP_DELAY_SECONDS = 1.0
DEFAULT_BOARD_RUNTIME_STOP_COOLDOWN_SECONDS = 3.0

DEFAULT_BOARD_NFC_BACKEND = "pn532_i2c"
DEFAULT_BOARD_NFC_I2C_BUS = 4
DEFAULT_BOARD_NFC_I2C_ADDRESS = 0x24
DEFAULT_BOARD_NFC_SCAN_TIMEOUT = 3.0
DEFAULT_BOARD_NFC_PASSIVE_ACTIVATION_RETRIES = 0x02
DEFAULT_BOARD_NFC_FALLBACK_TO_UID = False
DEFAULT_BOARD_NFC_POLL_ENABLED = True
DEFAULT_BOARD_NFC_POLL_INTERVAL = 0.5

DEFAULT_BOARD_VIBRATION_BACKEND = "mpu6050"
DEFAULT_BOARD_MPU6050_I2C_BUS = 3
DEFAULT_BOARD_MPU6050_I2C_ADDRESS = 0x68
DEFAULT_BOARD_MPU6050_YELLOW_THRESHOLD = 0.18
DEFAULT_BOARD_MPU6050_RED_THRESHOLD = 0.35

DEFAULT_BOARD_CONTROL_UART_PORT = "/dev/ttyS5"
DEFAULT_BOARD_CONTROL_UART_BAUDRATE = 115200
DEFAULT_BOARD_CONTROL_UART_TIMEOUT = 1.0

DEFAULT_BOARD_SERVO_BACKEND = "stm32_uart"
DEFAULT_BOARD_CONVEYOR_BACKEND = "stm32_uart"
DEFAULT_BOARD_SERVO_NORMAL_ANGLE = 90
DEFAULT_BOARD_SERVO_SORT_ANGLE = 45
DEFAULT_BOARD_SERVO_SORT_SECONDARY_ANGLE = 20

DEFAULT_BOARD_CONVEYOR_SPEED_MODE = "hz"
DEFAULT_BOARD_CONVEYOR_FULL_SPEED_HZ = 60
DEFAULT_BOARD_CONVEYOR_SPEED = DEFAULT_BOARD_CONVEYOR_FULL_SPEED_HZ
DEFAULT_BOARD_CONVEYOR_STEP_MAX_HZ = DEFAULT_BOARD_CONVEYOR_FULL_SPEED_HZ
DEFAULT_BOARD_CONVEYOR_HALF_TRAVEL_SECONDS = 10.0

DEFAULT_BOARD_SORT_PREPARE_PAUSE_SECONDS = 0.0
DEFAULT_BOARD_SORT_SERVO_SETTLE_SECONDS = 0.2
DEFAULT_BOARD_SORT_SERVO_OSCILLATION_INTERVAL = 0.5
# 当前机械链路上，异常件从识别位继续运行到完全通过拨料位置，经验值约为 10 秒。
DEFAULT_BOARD_SORT_CONVEYOR_ADVANCE_SECONDS = DEFAULT_BOARD_CONVEYOR_HALF_TRAVEL_SECONDS


__all__ = [
    "DEFAULT_BOARD_CAMERA_ID",
    "DEFAULT_BOARD_CAMERA_FPS",
    "DEFAULT_BOARD_CAMERA_WEB_FPS",
    "DEFAULT_BOARD_CAMERA_CLASSIFICATION_FPS",
    "DEFAULT_BOARD_CAMERA_WIDTH",
    "DEFAULT_BOARD_CAMERA_HEIGHT",
    "DEFAULT_BOARD_CAMERA_FORMAT",
    "DEFAULT_BOARD_RUNTIME_CENTER_HOLD_FRAMES",
    "DEFAULT_BOARD_RUNTIME_STOP_ON_FIRST_DETECTION",
    "DEFAULT_BOARD_RUNTIME_DETECTION_STOP_DELAY_SECONDS",
    "DEFAULT_BOARD_RUNTIME_STOP_COOLDOWN_SECONDS",
    "DEFAULT_BOARD_NFC_BACKEND",
    "DEFAULT_BOARD_NFC_I2C_BUS",
    "DEFAULT_BOARD_NFC_I2C_ADDRESS",
    "DEFAULT_BOARD_NFC_SCAN_TIMEOUT",
    "DEFAULT_BOARD_NFC_PASSIVE_ACTIVATION_RETRIES",
    "DEFAULT_BOARD_NFC_FALLBACK_TO_UID",
    "DEFAULT_BOARD_NFC_POLL_ENABLED",
    "DEFAULT_BOARD_NFC_POLL_INTERVAL",
    "DEFAULT_BOARD_VIBRATION_BACKEND",
    "DEFAULT_BOARD_MPU6050_I2C_BUS",
    "DEFAULT_BOARD_MPU6050_I2C_ADDRESS",
    "DEFAULT_BOARD_MPU6050_YELLOW_THRESHOLD",
    "DEFAULT_BOARD_MPU6050_RED_THRESHOLD",
    "DEFAULT_BOARD_CONTROL_UART_PORT",
    "DEFAULT_BOARD_CONTROL_UART_BAUDRATE",
    "DEFAULT_BOARD_CONTROL_UART_TIMEOUT",
    "DEFAULT_BOARD_SERVO_BACKEND",
    "DEFAULT_BOARD_CONVEYOR_BACKEND",
    "DEFAULT_BOARD_SERVO_NORMAL_ANGLE",
    "DEFAULT_BOARD_SERVO_SORT_ANGLE",
    "DEFAULT_BOARD_SERVO_SORT_SECONDARY_ANGLE",
    "DEFAULT_BOARD_CONVEYOR_SPEED_MODE",
    "DEFAULT_BOARD_CONVEYOR_FULL_SPEED_HZ",
    "DEFAULT_BOARD_CONVEYOR_SPEED",
    "DEFAULT_BOARD_CONVEYOR_STEP_MAX_HZ",
    "DEFAULT_BOARD_CONVEYOR_HALF_TRAVEL_SECONDS",
    "DEFAULT_BOARD_SORT_PREPARE_PAUSE_SECONDS",
    "DEFAULT_BOARD_SORT_SERVO_SETTLE_SECONDS",
    "DEFAULT_BOARD_SORT_SERVO_OSCILLATION_INTERVAL",
    "DEFAULT_BOARD_SORT_CONVEYOR_ADVANCE_SECONDS",
]
